---
output: html_document
---

# Libro de Códigos

## Libro de Códigos de Muestra

El propósito de este documento es establecer un libro de códigos para estudiantes aprendiendo a estandarizar relacionales.

### Relaciones

#### Persona-a-persona (modo-uno) {-}

Las siguientes definiciones son ejemplos de relaciones de modo-uno entre personas. Estas solo deben tomarse como ejemplos, le recomendamos que adapte el contenido para adaptarlo a su investigación.

  - **Amistad** (persona-a-persona): definida como dos personas que se declaran explícitamente como amigos, o que se conocen explícitamente como confidentes de confianza, en informes o en documentación de inteligencia. Los casos de relaciones familiares autoidentificables en las que dos o más personas se consideran familiares, pero que no están relacionadas por sangre, matrimonio o adopción, también se consideran un ejemplo de este tipo de relación.

  - **Asociado criminal** (persona-a-persona): definido como dos individuos que colaboran, ayudan o participan directamente en actividades ilícitas, incluidas acciones criminales fuera de línea y en línea, como compartir sustancias y / o transferir material ilegal.

  - **Compañeros de clase** (persona-a-persona): dos personas que asisten, como estudiantes, a la misma institución académica, al mismo tiempo. Una institución académica se define como cualquier institución dedicada a proporcionar educación. Los ejemplos pueden incluir, entre otros, cursos de capacitación, escuelas primarias, escuelas intermedias, escuelas secundarias y colegios y universidades.

  - **Comunicación** (persona-a-persona): definida como la transmisión directa, en persona, de mensajes o información entre individuos o mediante algún tipo de medio, como un teléfono celular o un correo electrónico.

  - **Financieras** (persona a persona): definido como dos actores, en informes o inteligencia, que se declaran explícitamente como transfiriendo fondos entre sí para cualquier propósito, legal o ilegal. Esta relación, sin embargo, NO incluye la compensación normal entre empleador y empleado.

 - **Reclutador** (persona-a-persona): se define como el contacto entre dos personas con el fin de reclutar nuevos miembros para actividades relacionadas con una organización.
 
  - **Relaciones Superior-Subordinado** (persona-a-persona) - Definidas como relaciones entre superiores inmediatos y subordinados en una organización. Esta relación explica los lazos formales / jerárquicos dentro de las organizaciones ilegítimas.

  - **Romance** (persona-a-persona): definido como una relación cariñosa y romántica entre dos o más personas. Los ejemplos de esta categoría incluyen las relaciones no matrimoniales, como una en la que dos personas tienen un hijo (o hijos) juntos, que están involucrados en relaciones sexuales entre ellos y aquellos que están saliendo o cortejándose.

#### Persona-a-Evento (modo-dos) {-}

Las siguientes definiciones son ejemplos de relaciones de modo-dos entre personas y eventos. Estas solo deben tomarse como ejemplos, le recomendamos que adapte el contenido para adaptarlo a su investigación.

  - **Evento criminal** (persona-a-evento): definido como la participación de una persona en un evento, reunión, suceso o incidente en el que el propósito, las metas o los resultados del evento relacionados con, o que resultaron en actividades criminales. Esta definición incluye personas que son testigos, perpetradores, co-arrestados y víctimas de incidentes criminales. Los ejemplos pueden incluir, entre otros, crímenes violentos, reuniones formales / informales y eventos de capacitación relacionados con actividades criminales o que resultaron en ellas.

  - **Evento no-criminal** (persona-a-evento): definido como la participación de una persona un evento, reunión, evento o incidente en el que el propósito del evento no se relaciona con actividades delictivas. Los ejemplos pueden incluir, entre otros, reuniones sociales, reuniones formales / informales, eventos comunitarios y eventos de capacitación que no están relacionados con actividades delictivas.

#### Persona-a-Locación or Material (modo-dos) {-}

Las siguientes definiciones son ejemplos de relaciones de modo-dos entre personas y locaciones or materiales. Estas solo deben tomarse como ejemplos, le recomendamos que adapte el contenido para adaptarlo a su investigación.

  - **Evidencia** (persona-a-material): definida como la relación física o la asociación directa de un individuo con un elemento de evidencia, como la posesión o el control individual de narcóticos, armas, documentos, etc.
  
  - **Residencia** (persona-a-locación): definida como la propiedad, el alquiler una persona a una casa, un apartamento, un condominio, un piso, una casa de seguridad o cualquier otro tipo de residencia. Esta opción también puede incluir la propiedad, el alquiler y las visitas a residencias en el pasado.
  
#### Persona-a-Organización (modo-dos) {-}

Las siguientes definiciones son ejemplos de relaciones de modo-dos entre personas y organizaciones. Estas solo deben tomarse como ejemplos, le recomendamos que adapte el contenido para adaptarlo a su investigación.

  - **Afiliación con organizaciones ilegítimas** (persona-a-organización): definida como la propiedad, el empleo y / o la membresía de una persona en una organización ilegítima. Una organización ilegítima se define como un grupo u organización cuyos objetivos son de naturaleza criminal (terrorista), o que voluntariamente obtiene recursos materiales y / o no materiales a través de actividades delictivas.
  
  - **Afiliación con organizaciones legítimas** (persona-a-organización): definida como la propiedad, el empleo y / o la membresía de una persona en una organización legítima. Una organización legítima se define como aquella que se abstiene de participar, apoyar o estar involucrada en actividades delictivas. Los ejemplos incluyen, entre otros, las siguientes organizaciones: organizaciones comunitarias, con fines de lucro, organizaciones sin fines de lucro, organizaciones políticas, organizaciones religiosas, e instituciones académicas. 
  
### Atributos

Esta sección describe y define los atributos (es decir, las características) de los actores.

  - **Afiliación con organizaciones ilegítimas**: definida como la propiedad, el empleo y / o la membresía de una persona en una organización ilegítima. Una organización ilegítima se define como un grupo u organización cuyos objetivos son de naturaleza nefasta (es decir, criminal) o que voluntariamente obtiene recursos materiales y / o no materiales a través de actividades ilegales.
    
 - **Afiliación con organizaciones legítimas**: definida como la propiedad, el empleo y / o la membresía de una persona en una organización legítima. Una organización legítima se define como aquella que se abstiene de participar, apoyar o estar involucrada en actividades delictivas.
    
  - **Dirección**: la (s) ubicación (es) específica (s) en la que reside una persona.

  - **Raza / origen étnico**: definido como el grupo racial o étnico con el que el individuo se identifica. Un grupo étnico es un grupo social al que pertenece una persona y que comparte una cultura, religión o idioma común y distintivo.

  - **Ideología / creencia:** definida como el sistema de ideas y creencias de un individuo, incluidas las creencias políticas y económicas.

  - **Ocupación**: definida como el título funcional actual de empleo de un individuo.
  
  - **Rol**: definido como un rol que un individuo asume en una organización legítima o ilegítima. Los codificadores de datos pueden registrar varios roles dado que la mayoría de los actores tienen más de un rol.

  - **Habilidades (tecnológicas)**: definidas como habilidades especiales relacionadas con la tecnología, independientemente del dominio o campo que posea (por ejemplo, piratería informática).

  - **Habilidades (no tecnológicas)**: definidas como habilidades especiales NO relacionadas con la tecnología, independientemente del dominio o campo que posea (por ejemplo, habilidades de las personas).

  - **Estado**: definido como la condición física del individuo. El valor predeterminado es "Vivo y libre" si falta información o si el estado físico de un actor es "desconocido". Por ejemplo:
    - Vivo y libre
    - Encarcelado / detenido
    - Muerto


## Libro de Códigos de Noordin Top

El contenido de este libro de códigos es atribuido a la Profesora Nancy Roberts, el Profesor Sean Everton y Dan Cunningham en Laboratorio CORE [@Roberts2014]. El libro de códigos corresponde a los datos de las redes de Nordin Top y sus colaboradores en el grupo terrorista Jemaah Islamiya. Estos datos se obtuvieron principalmente de dos informes de International Crisis Group (ICG): "Terrorism in Indonesia: Noordin’s Networks" [@ICG2006] e "Indonesia: Noordin Top’s Support Base" [@ICG2009]. Los dos informes del ICG sobre Noordin contienen datos valiosos de modo-uno y dos sobre una variedad de relaciones y afiliaciones (amistad, parentesco, reuniones, etc.) junto con datos de atributos importantes (educación, pertenencia al grupo, estado físico, etc.). Los datos fueron inicialmente estructurados y analizados por estudiantes de la Escuela de Postgrado Naval en el curso "Seguimiento y Disrupción de las Redes Oscuras" bajo la dirección del Profesor Sean Everton, Co-Director del Laboratorio CORE y la Profesora Nancy Roberts y luego expandidos y limpiados por la Facultad Asociada para Instrucción, Dan Cunningham. 

### Relaciones

  - **Afiliación Organizacional** (modo-dos 237 x 32): Una organización terrorista/insurgente se define como un sistema administrativo y funcional, cuyo principal objetivo común es la conducta operativa de actividades terroristas/insurgentes, que consiste en miembros voluntariamente afiliados. A los efectos de este ejercicio, las facciones se considerarán separados de su organización principal para evitar que se codifiquen vínculos redundantes. En otras palabras, la mayoría de las afiliaciones de nivel micro están codificadas, mientras que un individuo solo se codifica en la organización principal si no figura como afiliado a una organización secundaria. Las organizaciones afiliadas terroristas / insurgentes, también están codificadas en esta matriz.

  - **Afiliación Educativa** (modo-dos 237 x 25): Las relaciones educativas se definen como escuelas donde las personas reciben educación formal, sirven como empleados (maestro, administrador, etc.) y/o participan en instrucción educativa o religiosa adicional en la institución.
  
  - **Compañeros de clase/colegas educativos** (modo-uno 237 x 237): Los compañeros de clase/colegas educativos se definen como personas que reciben educación formal, sirven como empleados (maestro, administrador, etc.) y/o participan en instrucción educativa o religiosa adicional en la misma institución y al mismo tiempo. Es más probable que esta relación refleje relaciones precisas que la matriz de "afiliación educativa" de dos modos, ya que considera el tiempo en el que las personas están presentes en una escuela.
  
::::{.infobox .note data-latex="note"}
**Nota de autor:** La codificación en la hoja maestra será diferente de la codificación basada únicamente en el informe del ICG. El primero utilizó información fuera del informe "Noordin’s Networks" del ICG para establecer si las personas podían considerarse compañeros de clase/colegas educativos según la definición.
::::

  - **Lazos de Comunicación** (modo-uno 237 x 237): La comunicación interna se define como la transmisión de mensajes entre individuos y/o grupos dentro de la red a través de algún tipo de medio.
  
  - **Medio para comunicación externa** (modo-dos 237 x 5): El medio de comunicación externa se define como los diversos medios utilizados para transmitir información entre personas dentro y fuera de la red. Estos son:
    - Mensajes de computadora, como sitios web (www.anshar.net), cafés de red y correo electrónico.
    - Medios impresos, como la revista KOMPAK
    - Material de apoyo (códigos y contraseñas): para enviar material desde la prisión
    - Desconocido: cualquier tipo de comunicación no definido pero referenciado entre miembros
    - Vídeos: para la fabricación de bombas y la formación para reclutar miembros externos
    
  - **Lazos de parentesco** (modo-uno 237 x 237): El parentesco se define como cualquier vínculo familiar, como hermano, cuñado, sobrino, etc. El parentesco también incluirá los matrimonios actuales y los matrimonios pasados ​​debido a divorcios y/o muertes.
  
  - **Eventos de Entrenamiento** (modo-dos 237 x 15): Participación en cualquier actividad específicamente designada para enseñar el conocimiento, las habilidades y las competencias del terrorismo y la insurgencia. El entrenamiento no incluye la participación en un acto patrocinado por terroristas o actividad muyahidín en lugares como Afganistán, Bosnia, Chechenia o Irak, a menos que la presencia de las personas fuera para participar en un campo de entrenamiento o base específicamente designado en una de estas áreas.

::::{.infobox .note data-latex="note"}
**Nota de autor:** Las personas que participaron en la "Capacitación religiosa de la embajada de Australia" y/o la "Capacitación para Bali II en el restaurante 'Selera'" pueden reflejar vínculos redundantes con la "Red de operaciones", ya que algunas personas participaron en estas capacitaciones específicas de la Embajada de Australia (04 de septiembre) y las operaciones de Bali II (05 de octubre).
::::

  - **Lazos de reclutamiento** (modo-uno 237 x 237): Contacto entre dos personas con el fin de reclutar nuevos miembros para actividades relacionadas con el terrorismo o la insurgencia. Las relaciones de reclutamiento solo son relevantes cuando el intento de reclutar miembros ha tenido éxito. No se incluyen los intentos de reclutamiento fallidos.
  
::::{.infobox .note data-latex="note"}
**Nota de autor:** Estos lazos crean una red dirigida y no deben ser simétricos en la matriz. Además, los reclutadores están en las filas mientras que los reclutados están en las columnas.
::::

  - **Afiliaciones comerciales** (modo-dos 237 x 11): Definidas como organizaciones con y sin fines de lucro que emplean personas.
  
  - **Afiliaciones de negocios y finanzas** (modo-dos 237 x 12): Definidas como organizaciones con y sin fines de lucro que emplean a personas (incluye la Fundación Durassalam).

  - **Tipo de financiación** (modo-dos 237 x 5): Las relaciones financieras se definen como la provisión de fondos (legales e ilegales) para respaldar, mantener y realizar operaciones para la red.
  
  - **Operaciones** (modo-dos 237 x 14): Las relaciones operativas se definen como personas que participan  en la preparación, ejecución yo prestación de apoyo posoperatorio. La preparación debe relacionarse directamente con la operación y puede incluir objetivos reconocimiento, proporcionar refugio seguro para la preparación, contribuir al entrenamiento religioso y/o físico y participar en un robo donde las ganancias financian un ataque posterior. La prestación de apoyo posterior a la operación, como la ocultación de fugitivos y la eliminación de explosivos, también debe estar directamente relacionada con la operación.
  
  - **Amistad** (modo-uno 237 x 237): Las relaciones de amistad se definen como vínculos estrechos a través del afecto o la estima entre dos personas. Los lazos de amistad no se definen únicamente como reuniones y/o vínculos escolares.
  
::::{.infobox .note data-latex="note"}
**Nota de autor:** Las relaciones de amistad pueden ser extremadamente subjetivas si no se establecen explícitamente en el documento. Normalmente, las relaciones implícitas se basan en relaciones estrechas y coherentes a lo largo del tiempo. La relación entre Noordin Top y Azhari Husin, por ejemplo, no se declara explícitamente como una amistad en el documento, pero fueron colaboradores cercanos durante muchos años.
::::

  - **Afiliación religiosa** (modo-dos 237 x 8): Las relaciones religiosas se definen como una asociación con una mezquita, iglesia, sinagoga o círculo de estudio religioso. Los círculos de estudio religioso solo se codifican si están separados de otras entidades religiosas (es decir, mezquita). No incluimos las escuelas islámicas aunque asumimos que las escuelas tienen mezquitas. No utilizar las escuelas evita la duplicación de esfuerzos con el equipo que construye los lazos escolares. Además, enumeramos las mezquitas por la ciudad en la que se encuentra. Si había más de uno en una ciudad, agregamos un identificador numérico más el nombre de la ubicación más cercana.
  
  - **Almas gemelas** (modo-uno 237  x 237): Las relaciones de alma gemela se definen como personas que están afiliadas a la misma institución religiosa al mismo tiempo. Es más probable que esta relación indique vínculos religiosos precisos que la “afiliación religiosa”, ya que considera los períodos de tiempo en los que las personas están afiliadas a instituciones religiosas.
  
::::{.infobox .note data-latex="note"}
**Nota de autor:** La codificación en la hoja maestra diferirá considerablemente de la codificación basada únicamente en el informe del ICG. El primero utilizó información fuera del informe del ICG para determinar los plazos en los que las personas estaban afiliadas a una institución religiosa.
::::

  - **Lugar logistico** (modo-dos 237 x 35): Las relaciones logísticas se definen como un lugar clave dentro del archipiélago donde ocurrió la actividad logística. La actividad logística se define como proporcionar "casas seguras" para reunirse/esconderse, brindar apoyo material en términos de explosivos, proporcionar armamento o facilitar el transporte de personal o equipo.

  - **Función logística** (modo-dos 237 x 4): Las funciones logísticas se definen como el apoyo a operaciones terroristas/insurgentes proporcionando materiales, armas, transporte y refugios.
  
  - **Lazos de mentores: ideológicos, supervisorese y tecnológicos** (modo-uno 237 x 237): Las subredes ideológicas, de supervisión y técnicas identifican a las personas en la red de Noordin que poseen la autoridad para dar el "Cómo", el "Qué" y el "Por qué" al resto de la red. Sentimos que la autoridad religiosa, la habilidad técnica como la fabricación de bombas o la habilidad informática, y el liderazgo comprobado eran habilidades que no se podían transferir fácilmente y valdría la pena centrarse en interrumpir la red.
  
::::{.infobox .note data-latex="note"}
**Nota de autor:** Estas redes son dirigidas y no deben ser simétricas. Además, los mentores están en las filas mientras que los mentoreados están en las columnas.
::::

  - **Rol** (modo-dos 237 x 16): Definido como el papel que asume un individuo en la red terrorista/insurgencia. Codificado como datos de dos modos (ver también datos de atributos de función principal a continuación) porque algunas personas cumplen más de una función. La presencia de un rol por parte de un individuo se codificó como 1 y la ausencia como 0.

  - **Reuniones** (modo-dos 237 x 20): Un evento coordinado y planificado de antemano entre dos o más personas. Las reuniones no incluyen todos los estilos de comunicación. Por el contrario, reunión se refiere a un lugar determinado en una fecha determinada con personas específicas. Las reuniones infieren la necesidad de una decisión, pero los datos no identifican específicamente la decisión o el tema de la reunión.
  
  - **Entidades diversas** (modo-dos 237 x 10): Estas relaciones indican afiliación, pero no entran dentro de la definición de otras relaciones. Estas entidades van desde sitios web hasta campamentos militares y organizaciones políticas.


### Atributos

   - **Nivel de educación**: definido como el título más alto alcanzado, el nivel en el que se enseñó, estudió, participó o asistió. El siguiente es el esquema de códigos:
   
| Código      | Description |
| ----------- | ----------- |
| 0           | Desconocido |
| 1           | Educación Primaria |
| 2           | Pesantren   |
| 3           | Escuela secundaria estatal |
| 4           | Algo de universidad |
| 5           | Universidad |
| 6           | Algo de maestría |
| 7           | Maestría    |
| 8           | Doctorado   |

  - **Contacto con personas fuera de Indonesia:** definido como contacto con personas en diferentes países fuera de Indonesia.
  
| Código      | Description |
| ----------- | ----------- |
| 0           | Desconocido |
| 1           | Afganistán  |
| 2           | Australia   |
| 3           | Malasia     |
| 4           | Pakistán    |
| 5           | Filipinas   |
| 6           | Singapur    |
| 7           | Tailandia   |
| 8           | Reino Unido |
| 9           | Afganistán y Malasia|
| 10          | Afganistán y Filipinas |
| 11          | Afganistán y Pakistán |
| 12          | Afganistán, Malasia y Filipinas |
| 13          | Australia y Malasia |
| 14          | Filipinas y Malasia |
| 15          | Afganistán, Pakistán y Egipto |
| 16          | Irak, Afganistán y Pakistán |

  - **Entrenamiento militar:** definido como el país donde un individuo recibió entrenamiento militar y alcanzó el estatus de veterano en la lucha en guerras insurgentes/convencionales conocidas.
  
| Código      | Description |
| ----------- | ----------- |
| 0           | Desconocido |
| 1           | Afganistán  |
| 2           | Australia   |
| 3           | Indonesia     |
| 4           | Malasia   |
| 5           | Filipinas   |
| 6           | Singapur    |
| 7           | Afganistán e Indonesia   |
| 8           | Afganistán y Filipinas |
| 9           | Indonesia y Malasia |
| 10          | Indonesia y Filipinas |
| 11          | Afganistán e Irak |

  - **Nacionalidad de la persona:** definida como país de nacimiento, ciudadanía o residencia.

| Código      | Description |
| ----------- | ----------- |
| 1           | Afganistán  |
| 2           | Australia   |
| 3           | Indonesia   |
| 4           | Malasia     |
| 5           | Filipinas   |
| 6           | Singapur    |
| 7           | Arabia Saudita |
| 8           | Jordania    |
| 9           | Egipto      |

  - **Estado actual según el artículo del ICG:** definido como la condición física del individuo.
  
| Código      | Description |
| ----------- | ----------- |
| 0           | Muerto      |
| 1           | Vivo        |
| 2           | Encarcelado |

  - **Rol (Original):** definido como el rol que asume un individuo en la red terrorista/insurgente.
  
| Código      | Description |
| ----------- | ----------- |
| 0           | Sin información/poca claridad |
| 1           | Estratega: Planificador de alto nivel de una red terrorista/insurgente |
| 2           | Fabricante de bombas: Individuo que construye bombas |
| 3           | Bombardero/combatiente: Individuo que participa en ataques con bombas o que se describe como un combatiente |
| 4           | Entrenador/instructor: Individuo que entrena o instruye a nuevos miembros de una red terrorista    |
| 5           | Terrorista suicida: Individuo que planea o ya ha realizado un ataque suicida  |
| 6           | Reconocimiento y vigilancia: Participa en la vigilancia y reconocimiento de objetivos |
| 7           | Reclutador: Se dedica a identificar y reclutar nuevos miembros (para incluir bombarderos)   |
| 8           | Mensajero /Intermediario: Facilita las comunicaciones entre miembros |
| 9           | Propagandista: Desarrolló campañas de información|
| 10          | Facilitador: Asistido en el funcionamiento de la red (especialmente con materiales y finanzas) |
| 11          | Líder religioso: Se le proporcionó formación y apoyo religiosos |
| 12          | Comandante/Líder táctico: A cargo de las operaciones a nivel local/táctico |

  - **Rol ampliado (primario y secundario):** Definido como el rol que asume un individuo en la red terrorista/insurgente (incluye roles primarios y secundarios).
  
| Código      | Description |
| ----------- | ----------- |
| 1           | Fabricante de bombas |
| 2           | Bombardero |
| 3           | Mensajero |
| 4           | Facilitador |
| 5           | Líder |
| 6           | Enlace |
| 7           | Líder local |
| 8           | Propagandista |
| 9           | Reclutador |
| 10          | Líder religioso |
| 11          | Maestro religioso, mentor, motivador |
| 12          | Proveedor de recursos |
| 13          | Estratega |
| 14          | Bombardero suicida |
| 15          | Simpatizante |
| 16          | Entrenador |
| 99          | No hay datos |

  - **Función logística:** definida como la provisión de casas seguras, armas, transporte y/o material a la red operativa.

| Código      | Description |
| ----------- | ----------- |
| 1           | Proporcionar una casa segura |
| 2           | Suministro de armas |
| 3           | Proporcionar transporte |
| 4           | Suministro de material |
| 5           | Suministro de armas, transporte y material |
| 6           | Suministro de armas, material |
| 7           | Suministro de transporte, material |
| 8           | Proporcionar refugio y transporte |
| 9           | Proporcionar refugio, transporte, material |
| 10          | Proporcionar refugio, armas, material |

  - **Habilidades técnicas:** elegimos codificar los atributos técnicos en función de los conjuntos de habilidades explícitos mencionados en el informe del ICG. En contraste con un atributo como "rol", elegimos solo codificar las habilidades técnicas específicas que se enumeran a continuación y no consideramos cosas como "líder de celda" o "financiero" como un rol técnico. Básicamente, estábamos buscando habilidades relacionadas con la electrónica, fabricación de bombas, diseño de páginas web, etc. A continuación se muestra una lista de los roles y el número correspondiente que recibió cada individuo. En los casos en que alguien tenía múltiples habilidades técnicas, elegimos codificar la que es subjetivamente más relevante para las operaciones terroristas. Por ejemplo, Azhari Husin tiene experiencia en ingeniería mecánica pero también tiene entrenamiento en explosivos. Lo codificaríamos como "fabricación de bombas". Aquellos sin habilidades técnicas identificadas reciben un 0 en la matriz.

| Código      | Description |
| ----------- | ----------- |
| 1           | Fabricación de bombas |
| 2           | Propaganda (producción de videos y CD de video, revistas, diseño de páginas web, etc.) |
| 3           | Instrucción de habilidades militares (artes marciales, tiro, etc.) |
| 4           | Otro conocimiento avanzado (ingeniería mecánica, agricultura, etc.) |
| 5           | Instrucción religiosa |

  - **Afiliación de grupo principal:** definida como la afiliación de grupo principal de cada miembro de la red, en general.

| Código      | Description |
| ----------- | ----------- |
| 0           | Ninguno (Noordin) |
| 1           | Darul Islam (DI) |
| 2           | KOMPAK |
| 3           | Jemaah Islamiyah (JI) |
| 4           | Ring Banten Group (DI) |
| 5           | Al-Qaeda |

  - **Red de Noordin:** un individuo que se considera miembro del grupo de Noordin (Tanzim Qaedat al-Jihad - Organización para la base del Jihad), en lugar de simplemente estar vinculado. Igualmente, si el individuo participó en una operación dirigida por Noordin durante cualquier etapa. Finalmente, si él o ella se declara explícitamente como miembro del círculo íntimo de Noordin y/o está vinculado a Noordin por parentesco o amistad.

| Código      | Description |
| ----------- | ----------- |
| 0           | No es miembro |
| 1           | Miembro |

  - **Original 79:** Definido como las 79 personas enumeradas en el apéndice del Informe del ICG de 2006, "Noordin’s Networks"

| Código      | Description |
| ----------- | ----------- |
| 0           | No incluido en el Apéndice |
| 1           | Incluido en el Apéndice |
